# @format

name: CI
on: [push, workflow_dispatch]

# RUNNING_ON_PROD KUBECONFIG

jobs:
  plasmic-ci:
    runs-on: ubuntu-latest
    # You need to use the INSTALLATION_NAME from the previous step
    #    container: plasmicapp/arc-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 8
      - uses: actions/cache@v3
        with:
          path: |
            out
          key: ${{ runner.os }}-yarn-${{ hashFiles('in') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('in') }}
            ${{ runner.os }}-yarn-
      - run: |
          mkdir -p out
          tail out/* || true
          bash in
